// ─────────────────────────────────────────────
//  data.js  —  Sample lead data (replace via Google Sheets sync)
// ─────────────────────────────────────────────

const leads = [
  {
    id: 'l1',
    name: 'Sarah Johnson',
    title: 'VP of Marketing',
    company: 'Stripe',
    about: 'Global fintech leader in online payment processing and financial infrastructure for the internet.',
    summary: 'Sarah has 8 years at Stripe scaling B2B marketing across EMEA and North America, focused on enterprise SaaS sales cycles and demand gen.',
    score: 92,
    status: 'Hot',
    linkedinUrl: 'https://linkedin.com',
    landingUrl: '#',
    avClass: '',
    avInit: 'SJ',
    pipeline: {
      conn_sent: 'done', conn_accepted: 'done', msg1_sent: 'active',
      msg1_replied: 'pending', msg2_sent: 'pending', msg2_replied: 'pending',
      msg3_sent: 'pending', msg3_replied: 'pending',
    },
    pipeTimestamps: {
      conn_sent: 'Jun 10, 2026 · 9:04 AM',
      conn_accepted: 'Jun 12, 2026 · 2:17 PM',
    },
    messages: { connection: '', msg1: '', msg2: '', msg3: '' },
    activity: [
      { icon: '✓', cls: 'ad-ok',      title: 'Connection Accepted',       body: 'Sarah accepted your connection request.',           time: 'Jun 12, 2:17 PM' },
      { icon: '→', cls: 'ad-info',    title: 'Connection Request Sent',   body: 'AI-generated note sent via LinkedIn.',              time: 'Jun 10, 9:04 AM' },
      { icon: '✨', cls: 'ad-ai',     title: 'AI Message Generated',      body: 'Connection note generated via GPT-4o.',             time: 'Jun 10, 9:02 AM' },
      { icon: '+', cls: 'ad-neutral', title: 'Lead Added',                body: 'Imported from Google Sheets · Score: 92',           time: 'Jun 8, 10:00 AM' },
    ],
  },
  {
    id: 'l2',
    name: 'Marcus Reid',
    title: 'Head of Growth',
    company: 'Notion',
    about: 'All-in-one workspace for notes, docs, project management and team collaboration.',
    summary: 'Marcus drives PLG strategy at Notion, previously built growth loops at Dropbox. Deep interest in B2B SaaS bottoms-up adoption models.',
    score: 87,
    status: 'Warm',
    linkedinUrl: 'https://linkedin.com',
    landingUrl: '#',
    avClass: 'av-green',
    avInit: 'MR',
    pipeline: {
      conn_sent: 'done', conn_accepted: 'done', msg1_sent: 'done',
      msg1_replied: 'done', msg2_sent: 'pending', msg2_replied: 'pending',
      msg3_sent: 'pending', msg3_replied: 'pending',
    },
    pipeTimestamps: {
      conn_sent: 'Jun 8, 2026 · 11:20 AM',
      conn_accepted: 'Jun 9, 2026 · 3:45 PM',
      msg1_sent: 'Jun 11, 2026 · 10:00 AM',
      msg1_replied: 'Jun 12, 2026 · 8:30 PM',
    },
    messages: { connection: '', msg1: '', msg2: '', msg3: '' },
    activity: [
      { icon: '↩', cls: 'ad-ok',      title: '1st Message Replied',    body: 'Marcus replied to your intro message.',   time: 'Jun 12, 8:30 PM' },
      { icon: '💬', cls: 'ad-info',   title: '1st Message Sent',       body: 'Intro message sent.',                     time: 'Jun 11, 10:00 AM' },
      { icon: '+', cls: 'ad-neutral', title: 'Lead Added',             body: 'Imported from Google Sheets · Score: 87', time: 'Jun 7, 9:00 AM' },
    ],
  },
  {
    id: 'l3',
    name: 'Priya Nair',
    title: 'Director of Sales',
    company: 'Figma',
    about: 'Collaborative interface design tool used by designers, developers and product teams worldwide.',
    summary: 'Priya leads enterprise sales at Figma, managing Fortune 500 relationships. Background in SaaS sales at Adobe and Salesforce.',
    score: 78,
    status: 'Warm',
    linkedinUrl: 'https://linkedin.com',
    landingUrl: '#',
    avClass: 'av-cyan',
    avInit: 'PN',
    pipeline: {
      conn_sent: 'done', conn_accepted: 'active', msg1_sent: 'pending',
      msg1_replied: 'pending', msg2_sent: 'pending', msg2_replied: 'pending',
      msg3_sent: 'pending', msg3_replied: 'pending',
    },
    pipeTimestamps: { conn_sent: 'Jun 13, 2026 · 10:30 AM' },
    messages: { connection: '', msg1: '', msg2: '', msg3: '' },
    activity: [
      { icon: '→', cls: 'ad-info',    title: 'Connection Request Sent', body: 'Waiting for Priya to accept.',            time: 'Jun 13, 10:30 AM' },
      { icon: '+', cls: 'ad-neutral', title: 'Lead Added',              body: 'Imported from Google Sheets · Score: 78', time: 'Jun 12, 4:00 PM' },
    ],
  },
  {
    id: 'l4',
    name: "James O'Sullivan",
    title: 'Chief Revenue Officer',
    company: 'Intercom',
    about: 'Customer communications platform providing AI-powered customer service for SaaS companies.',
    summary: "James is CRO at Intercom with 12+ years in B2B revenue leadership. Previously VP Sales at Zendesk. Manages $200M+ ARR pipeline.",
    score: 95,
    status: 'Hot',
    linkedinUrl: 'https://linkedin.com',
    landingUrl: '#',
    avClass: 'av-orange',
    avInit: 'JO',
    pipeline: {
      conn_sent: 'done', conn_accepted: 'done', msg1_sent: 'done',
      msg1_replied: 'active', msg2_sent: 'pending', msg2_replied: 'pending',
      msg3_sent: 'pending', msg3_replied: 'pending',
    },
    pipeTimestamps: {
      conn_sent: 'Jun 6, 2026 · 8:00 AM',
      conn_accepted: 'Jun 7, 2026 · 5:15 PM',
      msg1_sent: 'Jun 9, 2026 · 9:30 AM',
    },
    messages: { connection: '', msg1: '', msg2: '', msg3: '' },
    activity: [
      { icon: '💬', cls: 'ad-info',   title: '1st Message Sent', body: 'Waiting for reply.',       time: 'Jun 9, 9:30 AM' },
      { icon: '+', cls: 'ad-neutral', title: 'Lead Added',        body: 'Score: 95',               time: 'Jun 5, 11:00 AM' },
    ],
  },
  {
    id: 'l5',
    name: 'Lena Müller',
    title: 'SVP Product',
    company: 'Miro',
    about: 'Visual collaboration platform and online whiteboard for distributed teams and agile workflows.',
    summary: "Lena oversees Miro's product roadmap for enterprise features. Previously Director of Product at Atlassian, expert in remote-first culture.",
    score: 65,
    status: 'Cold',
    linkedinUrl: 'https://linkedin.com',
    landingUrl: '#',
    avClass: 'av-pink',
    avInit: 'LM',
    pipeline: {
      conn_sent: 'active', conn_accepted: 'pending', msg1_sent: 'pending',
      msg1_replied: 'pending', msg2_sent: 'pending', msg2_replied: 'pending',
      msg3_sent: 'pending', msg3_replied: 'pending',
    },
    pipeTimestamps: {},
    messages: { connection: '', msg1: '', msg2: '', msg3: '' },
    activity: [
      { icon: '+', cls: 'ad-neutral', title: 'Lead Added', body: 'Score: 65', time: 'Jun 13, 2:00 PM' },
    ],
  },
  {
    id: 'l6',
    name: 'David Park',
    title: 'CEO & Co-Founder',
    company: 'Rippling',
    about: 'Workforce management platform combining HR, payroll, IT and finance into a single unified system.',
    summary: 'David co-founded Rippling and scaled it to 4,000+ employees. Deeply involved in product strategy and enterprise partnerships.',
    score: 89,
    status: 'Qualified',
    linkedinUrl: 'https://linkedin.com',
    landingUrl: '#',
    avClass: 'av-purple',
    avInit: 'DP',
    pipeline: {
      conn_sent: 'done', conn_accepted: 'done', msg1_sent: 'done',
      msg1_replied: 'done', msg2_sent: 'done', msg2_replied: 'active',
      msg3_sent: 'pending', msg3_replied: 'pending',
    },
    pipeTimestamps: {
      conn_sent: 'Jun 1, 2026 · 9:00 AM',
      conn_accepted: 'Jun 2, 2026 · 4:00 PM',
      msg1_sent: 'Jun 4, 2026 · 10:00 AM',
      msg1_replied: 'Jun 5, 2026 · 3:30 PM',
      msg2_sent: 'Jun 8, 2026 · 9:00 AM',
    },
    messages: { connection: '', msg1: '', msg2: '', msg3: '' },
    activity: [
      { icon: '📨', cls: 'ad-info',   title: '2nd Message Sent',    body: 'Follow-up sent after 3 days.',       time: 'Jun 8, 9:00 AM' },
      { icon: '↩', cls: 'ad-ok',      title: '1st Message Replied', body: 'David responded positively!',        time: 'Jun 5, 3:30 PM' },
      { icon: '+', cls: 'ad-neutral', title: 'Lead Added',           body: 'Score: 89',                          time: 'Jun 1, 8:00 AM' },
    ],
  },
];
